theme: jekyll-theme-minimal
title: DongKyu Cho
description: MSc Data Science @ SNU, Representation Learning & Causality :coffee
logo: https://github.com/umamicode/umamicode.github.io/blob/main/dkcho.jpg
