theme: jekyll-theme-minimal
title: DongKyu Cho
description: MSc Data Science @ SNU, Representation Learning & Causality
logo: https://cynefin.io/images/thumb/0/04/Linear_causality_approach.jpg/300px-Linear_causality_approach.jpg
