theme: jekyll-theme-minimal
title: DongKyu Cho
description: MSc Data Science @ SNU, Representation Learning through the Causal Lens :coffee
logo: https://github.com/umamicode/umamicode.github.io/blob/main/dkcho.jpg
