theme: jekyll-theme-minimal
title: DongKyu Cho
description: |+
  MSc Data Science @ SNU 
  Causality & Representation Learning
logo: https://github.com/umamicode/umamicode.github.io/blob/main/dkcho.jpg?raw=true
